
spring:
  cloud:
    function:
      definition: Message
    stream:
      default-binder: local_rabbit
      bindings:
        emitSolaceMessage-in-0:
          destination: TEMPS.Q
          group: PROCESSOR
        emitSolaceMessage-out-0:
          destination: SOLACE/OUT_Q
      binders:
        local-solace:
          type: solace
          environment:
            solace:
              java:
                host: tcp://localhost:55555
                msgVpn: default
                clientUsername: admin
                clientPassword: admin
                connectRetries: -1
                reconnectRetries: -1
        local_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
                virtual-host: /
      solace:
        bindings:
          emitSolaceMessage-in-0:
            consumer:
              queueAdditionalSubscriptions: SOLACE/IN_Q

      rabbitmq:
        bindings:
          emitRabbitMessage-in-0:
            consumer:
              queueAdditionalSubscriptions: RABBIT_IN_Q
          emitRabbitMessage-out-0:
            consumer:
              queueAdditionalSubscriptions: RABBIT_OUT_Q

logging:
  level:
    root: INFO
    com.solacesystems.jcsmp: INFO
    org.springframework: INFO

server:
  port: 8999